### ISSUE TITLE
Who comes from MJD's MSN Explorer video?

### ISSUE THREAD

**Issue by leap0x7b** [brz/MarEx#2]
Not really an issue, but if you comes from MJD's MSN Explorer video, you can comment in this issue

**Comment by Aholicknight** [comment]
![Uploading Screen Shot 2021-01-16 at 12.39.22 AM.png…]()

**Comment by Aholicknight** [comment]
<img width="366" alt="Screen Shot 2021-01-16 at 12 39 52 AM" src="https://user-images.githubusercontent.com/7843719/104799267-5a327f80-5793-11eb-86a1-71d0e924096e.png">

**Comment by shiypc** [comment]
you probably shouldn't open issues if they aren't _really_ issues lol

**Comment by TheAwesome98-Real** [comment]
i didn't but this is issue spam and should be closed

**Comment by leap0x7b** [comment]
why did i open this

**Comment by TheAwesome98-Real** [comment]
we all do stupid stuff sometimes

**Comment by sctech-tr** [comment]
i did
